# -*- coding: utf-8 -*-
"""Praktik Grafika Komputer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqvCHvUa-CC6ME_1Zd7uuVQCMAlpChVj
"""

import matplotlib.pyplot as plt
# Membuat canvas 500 * 500
plt.figure(figsize = (5, 5))
# Menampilkan titik (x, y) dalam koordinat
x = [200]
y = [150]
plt.scatter(x , y, color= 'red', s = 50) #s = ukuran titik
plt.title('Plot titik pertama')
plt.xlim(0, 500)
plt.ylim(0, 500)
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
# Koordinat latihan mahasiswa
x = [50, 100, 150, 200, 250]
y = [60, 200, 300, 400, 450]

plt.figure(figsize=(5,5))
plt.scatter(x, y, color = 'blue', s = 80, marker = 'o')

plt.title('Latihan Mandiri - 5 Titik Baru')
plt.xlim(0, 500)
plt.ylim(0, 500)
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
x = [100, 200, 300, 400]
y = [200, 150, 250, 350]

plt.figure(figsize=(5,5))
plt.plot(x, y, color = 'green', marker = 'o', linewidth= 2) #titik dihubungkan garis

plt.title('Menghubungkan titik dengan garis')
plt.xlim(0, 500)
plt.ylim(0, 500)
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
x = [100, 300, 200, 100]
y = [100, 100, 300, 100]

plt.figure(figsize=(5,5))
plt.plot(x, y, color = 'green', marker = 'o', linewidth= 2) #titik dihubungkan garis

plt.title('Membuat Segitiga')
plt.xlim(0, 500)
plt.ylim(0, 500)
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Membuat data untuk lingkaran
radius = 150
center_x = 250
center_y = 250

theta = np.linspace(0, 2*np.pi, 100)
x = center_x + radius * np.cos(theta)
y = center_y + radius * np.sin(theta)

plt.figure(figsize=(5,5))
plt.plot(x, y, color = 'blue', linewidth= 2)

plt.title('Membuat Lingkaran')
plt.xlim(0, 500)
plt.ylim(0, 500)
plt.grid(True)
plt.gca().set_aspect('equal', adjustable='box') # Make sure the circle is not distorted
plt.show()

import matplotlib.pyplot as plt
x = [100, 300, 300, 100, 100]
y = [100, 100, 300, 300, 100]

plt.figure(figsize=(5,5))
plt.plot(x, y, color = 'green', marker = 'o', linewidth= 2) #titik dihubungkan garis

plt.title('Membuat Segiempat')
plt.xlim(0, 500)
plt.ylim(0, 500)
plt.grid(True)
plt.show()